### ISSUE TITLE
`@graphql-eslint/eslint-plugin` should include `tslib` as a dependency

### ISSUE THREAD

**Issue by lensbart** [B2o5T/graphql-eslint#1341]
Not entirely sure what causes the error, because a quick search through this project only reveals [one YAML file](https://github.com/B2o5T/graphql-eslint/blob/ba24f26bd98cf614ef0cf1a5503a4be49b10b469/pnpm-lock.yaml) including `tslib`.

When running `@graphql-eslint/eslint-plugin` in a project that uses [Yarn PnP](https://yarnpkg.com/features/pnp), the ESLint process fails with the following error:

```
[Error - 12:47:17 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Failed to load plugin '@graphql-eslint' declared in '.eslintrc.js#overrides[4]': @graphql-eslint/eslint-plugin tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

An easy workaround is to include the following in the root `.yarnrc.yml`:
```yml
# .yarnrc.yml
packageExtensions:
  # awaiting fix: https://github.com/B2o5T/graphql-eslint/issues/1341
  '@graphql-eslint/eslint-plugin@*':
    dependencies:
      tslib: '*'
```

and running `yarn` again. But a better solution would be to include `tslib` as a dependency in the `package.json` of `@graphql-eslint/eslint-plugin`

Using `@graphql-eslint/eslint-plugin` v3.14.0

Thank you!
