### ISSUE TITLE
`@graphql-eslint/eslint-plugin`’s `package.json` should include dependencies for its dependencies’ peer dependencies

### ISSUE THREAD

**Issue by lensbart** [B2o5T/graphql-eslint#1687]
This issue is similar to https://github.com/B2o5T/graphql-eslint/issues/1341

When running `yarn` in a project that has a dependency on `@graphql-eslint/eslint-plugin`, a couple of warnings are shown:

```
➤ YN0002: │ @graphql-eslint/eslint-plugin@npm:3.19.1 [07f45] doesn't provide cosmiconfig-toml-loader (pa2cdb), requested by graphql-config
➤ YN0002: │ @graphql-eslint/eslint-plugin@npm:3.19.1 [07f45] doesn't provide cosmiconfig-typescript-loader (p37c45), requested by graphql-config
```
This can be worked around by including the following in the root `.yarnrc.yml`:
```yml
packageExtensions:
  '@graphql-eslint/eslint-plugin@*':
    dependencies:
      cosmiconfig-toml-loader: '*'
      cosmiconfig-typescript-loader: '*'
```

Run `yarn` again, you’ll see the following additional warnings:

```
➤ YN0002: │ @graphql-eslint/eslint-plugin@npm:3.19.1 [07f45] doesn't provide @types/node (pa731f), requested by cosmiconfig-typescript-loader
➤ YN0002: │ @graphql-eslint/eslint-plugin@npm:3.19.1 [07f45] doesn't provide cosmiconfig (p54ff9), requested by cosmiconfig-typescript-loader
➤ YN0002: │ @graphql-eslint/eslint-plugin@npm:3.19.1 [07f45] doesn't provide ts-node (p9f9b5), requested by cosmiconfig-typescript-loader
➤ YN0002: │ @graphql-eslint/eslint-plugin@npm:3.19.1 [07f45] doesn't provide typescript (p88270), requested by cosmiconfig-typescript-loader
```

So a complete workaround is to include the following in the root `.yarnrc.yml`:
```yml
# .yarnrc.yml
packageExtensions:
  # awaiting fix: https://github.com/B2o5T/graphql-eslint/issues/1687
  '@graphql-eslint/eslint-plugin@*':
    dependencies:
      '@types/node': '*'
      cosmiconfig: '*'
      cosmiconfig-toml-loader: '*'
      cosmiconfig-typescript-loader: '*'
      ts-node: '*'
      typescript: '*'
```

But a better solution would be to include the dependencies listed above as a dependencies in the `package.json` of `@graphql-eslint/eslint-plugin`

Using `@graphql-eslint/eslint-plugin` v3.19.1

Thank you!

**Comment by B2o5T** [comment]
which version of `graphql-config` you are using?

**Comment by B2o5T** [comment]
> Is graphql-config a required dependency to use @graphql-eslint/eslint-plugin?

graphql-config is required dependency for `graphql-eslint` but you don't need to install it

**Comment by lensbart** [comment]
Oh, I see. From `yarn.lock`:

```
"@graphql-eslint/eslint-plugin@npm:^3.12.0":
  version: 3.12.0
  dependencies:
    graphql-config: ^4.3.6
```
